### ISSUE TITLE
Gatsby-remark-graph instead of gatsby-remark-flowchart?

### ISSUE THREAD

**Issue by fairuzi10** [liudonghua123/gatsby-remark-flowchart#2]
Is it correct to use gatsby-remark-graph in your readme title? I think it should have been 'gatsby-remark-flowchart'. It confuses me with another plugin named 'gatsby-remark-graph'. Thank you.

**Comment by liudonghua123** [comment]
`gatsby-remark-flowchart'`(based on [flowchat.js](http://flowchart.js.org/)) and `gatsby-remark-graph`(based on [mermaid](https://mermaidjs.github.io/)) are different, you can choose one which meets you need more better.
